services:
  postgres:
    container_name: skinet-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skinet
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5832:5432"
    restart: unless-stopped

volumes:
  postgres:
