name: Build docker images

on:
  push:
    branches: [ master ]

jobs:
  build-api:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build bootJar
        run: chmod +x gradlew && ./gradlew :skinet-api:bootJar

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: skinet-api
          path: skinet-api/build/libs/skinet-api.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: api.Dockerfile
          push: true
          tags: funbiscuit/skinet-api:latest

  build-ui:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install -g @angular/cli

      - name: Download dependencies
        working-directory: client
        run: npm install

      - name: Build client
        working-directory: client
        run: ng build

      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: skinet-ui
          path: client/dist/client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: client.Dockerfile
          push: true
          tags: funbiscuit/skinet-ui:latest
