name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-api:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build bootJar
        run: chmod +x gradlew && ./gradlew :skinet-api:bootJar

      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: skinet-api.jar
          path: skinet-api/build/libs/skinet-api.jar

  build-ui:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download dependencies
        working-directory: client
        run: npm install

      - name: Build client
        working-directory: client
        run: ng build

      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: skinet-ui
          path: client/dist/client
